[project]
name = "administer-aos"
description = "Administer's AOS service for distributing apps."
version = "3.2"
requires-python = ">=3.13"
authors = [{ name = "pyxfluff", email = "business@notpyx.me" }]
dependencies = [
    # HTTP
    "uvicorn",
    "fastapi",
    "httpx",

    # Utilities
    "Levenshtein",
    "colorthief",
    "pymongo",
    "pathlib",
    "nanoid",
    "orjson",

    # Discord
    "audioop-lts",
    "py-cord",

    # Git packages
    "indigo-logger @ git+https://github.com/iiPythonx/il",

    # Development
    "matplotlib"
]

urls.PrimaryServer = "https://administer.notpyx.me"

[project.scripts]
aos = "AOS.__main__:main"
